(load-file "~/.emacs.d/myEmacs/repos.el")
(load-file "~/.emacs.d/myEmacs/moveline.el")
(load-file "~/.emacs.d/myEmacs/interface.el")
(load-file "~/.emacs.d/myEmacs/keys.el")
(load-file "~/.emacs.d/myEmacs/backups.el")
(load-file "~/.emacs.d/myEmacs/startup.el")
