(setq inhibit-startup-message t)

(load-file "/home/william/.emacs.d/myEmacs/backups.el")
(load-file "/home/william/.emacs.d/myEmacs/repos.el")
(load-file "/home/william/.emacs.d/myEmacs/packages.el")
(load-file "/home/william/.emacs.d/myEmacs/functions.el")
(load-file "/home/william/.emacs.d/myEmacs/interface.el")
(load-file "/home/william/.emacs.d/myEmacs/tabbar.el")
(load-file "/home/william/.emacs.d/myEmacs/keys.el")
(load-file "/home/william/.emacs.d/myEmacs/filetypes.el")
(load-file "/home/william/.emacs.d/myEmacs/startup.el")
